# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7666ac9425854aba9c065124b5fbe6d9d210fd29968f4b8f9cb0181c60d96e38070501f4f9d5dca8bd48efd89edbb3adeaeed066fa294e5d0f1028b68a0d55ca

test:
  secret_key_base: cd5db411cb0d038c8e9c0a8989b604cb22b3718db2106c331f08cc122b62f030cb1b1dd7ee853379392f2640b7e4ef769380b1c6823d8be3ec23c19118fe2d92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
